### PR TITLE
Made color conversions public and added conversion from RGBColor to SwiftUI.Color

### PR DESCRIPTION
**Pull request by theisegeberg**
A very minor change. I needed to initialize my own LCH colors so I made all the colorspace types public and added initialisers. I also added a convenience method to create a SwiftUI.Color from a RGBColor.

### CODE REVIEW

**Comment by intitni** [comment]
Thanks for your pull request.

Sorry for the late reply, I am having a break these days.

Why do you need the convenience method to create SwiftUI.Color from RGBColor? I don't see it being used anywhere inside this package.

I don't quite get your need of initializing your own LCH colors. Do you mean that you have some LCH colors generated somewhere and want a smooth gradient from them? Or do you mean that you just need the color space part but not gradient generation?

If it's the first case, I reckon it would be better to only expose the initializers and toRGB methods, and even better if it can be an extension on SmoothGradientGenerator and keep toRGB internal. 

If it's the second case, I would suggest just copy the file to your project.

And it would be kind of you to fix some indentations to use 4 spaces.

**Comment by theisegeberg** [comment]
Sorry for the wrong indenting! And the surprise PR.

Actually I was using LCH color as input. So I was generating LCH colors elsewhere. And so I wanted to be able to bypass the RGBColor completely. I think the SwiftUI color thing was because I started using the framework more like a LCH, LAB, etc. color tool, and that blinded me a bit. It's for gradients, it makes sense to only expose those.

**Comment by intitni** [comment]
Hi, 

Are you still planning to update this pull request? I have created a branch (generate-gradient-from-other-colorspace-colors) to add generate methods for other colorspace colors. Not sure if it suits your needs.

**Comment by theisegeberg** [comment]
That's exactly what I needed! Thank you.

**Comment by intitni** [comment]
It's now available in version 0.2.0.

**Pull request closed without merging**
